### PR TITLE
cp sandbox1 to Population_Genetics_in_R

### PR DESCRIPTION
**Pull request by knausb**
Could @zkamvar and @sporangia approve this pull request? Thank you!

### CODE REVIEW

**Comment by zkamvar** [comment]
Shall I assume that, apart from my mis-guided addition earlier, this is exactly how it's represented on sandbox1? 

I ask because the web interface is really slow with this many changes and I want to do a quick comb through

**Comment by Tabima** [comment]
Yes. Its exactly the same as before your addition.

**Comment by zkamvar** [comment]
👍

**Comment by grunwald** [comment]
With the exception of the appendix function glossary  that needs to be updated and very minor edits I made to broaden the scope to include genomics. Parts 1 and 2 are virtually untouched.

**Comment by sporangia** [comment]
Sounds good.

**Comment by zkamvar** [comment]
As everyone is okay with the changes, I will merge the PR

**Pull request merged**
