### PR TITLE
created quality_control.Rmd

### PR DESCRIPTION
**Pull request by knausb**
If anyone is interested in reviewing this please do. Otherwise, I'll give it about a week and merge it myself.

### CODE REVIEW

**Comment by zkamvar** [comment]
My only comment on this would be a suggestion to make sure the code style is a bit more consistent.

**Comment by knausb** [comment]
Hi @zkamvar, thanks for the feedback! You're seeing something I didn't see. Could you please elaborate? Is this inconsistency within that page or among pages? Or is it among authors? If its the later then I think a solution would be to develop a style sheet for the document. Otherwise each author is likely to use a different style. An alternate perspective is that this exposes the audience to multiple styles.

P.S. Congrats on your visa!

**Comment by zkamvar** [comment]
Most of the inconsistencies are related to spacing between the `=` in argument assignment. For example: https://github.com/grunwaldlab/Population_Genetics_in_R/blame/be9ca62c4b363407e0481588f86ccedb5413f2e1/quality_control.Rmd#L104-L114

**Comment by zkamvar** [comment]
> An alternate perspective is that this exposes the audience to multiple styles.

In my experience, while the audience should be exposed to different styles, having them in the same tutorial is mostly just confusing to the learners.

> I think a solution would be to develop a style sheet for the document.

I think so, too. I would recommend the tidyverse style guide: http://style.tidyverse.org/

**Comment by knausb** [comment]
At 4eba5948f9f9f09bb444716f5f71d581180b87ea I learned to use `lintr`. Didn't agree with everything it complained about, but tried. @zkamvar how's it look now?

**Comment by zkamvar** [comment]
It looks good! Thank you for your efforts 👍. The only other nitpicky thing I can see is mixing single and double quotes, but that's up to you if you want to do a pass with some sed or perl magic.

**Pull request merged**
