### PR TITLE
rebuilt site post genomic merge

### PR DESCRIPTION
**Pull request by knausb**
The site was not rendering properly after the merge. I think this addresses these issues.

### CODE REVIEW

**Comment by knausb** [comment]
Oops, this repo is using `gh-pages` instead of `master`. Merging and pushing.

**Comment by zkamvar** [comment]
The site is still buggin. 

It's likely because the `includes/` and `_output.yml` are still in the directory (elements before rmarkdown developed the `_site.yml` workflow).

You may want to remove `includes/before_body.html` and `_output.yml`

**Comment by zkamvar** [comment]
> Oops, this repo is using gh-pages instead of master. Merging and pushing.

I changed it to master right after #23

**Comment by zkamvar** [comment]
> You may want to remove includes/before_body.html and _output.yml

heck, just remove `includes/` and `_output.yml`

**Comment by knausb** [comment]
I see it rendering correctly now. Anyone else? Thanks @zkamvar !

**Comment by zkamvar** [comment]
I wouldn't say this is correct: 
image

**Comment by knausb** [comment]
I see the old style, but consider that minor. The content is there and we can work on updating the style. @zkamvar do you see anything else?

**Comment by zkamvar** [comment]
Nope, everything else seems to be in order. I wasn't sure whether or not you were expecting production ready.

**Comment by knausb** [comment]
Well, I wasn't expecting it to be a perfect transition. Took @zkamvar 's advice and removed `_output.yml` and `include/`. We now have the new style. I think its coming together.

**Pull request merged**
